### PR TITLE
Rename references according to files being moved in the Canton repo

### PR DESCRIPTION
**Pull request by stefanobaghino-da**

### CODE REVIEW

**Comment by stefanobaghino-da** [comment]
@mziolekda Thanks, but this requires an approval from @digital-asset/daml-docs. 🙂

**Comment by mziolekda** [comment]
I realize that. But at least I have checked the paths with respect of the canton source and can vouch for their soundness. 
If that helps in getting the final approval from the docs team

**Comment by stefanobaghino-da** [comment]
I temporarily made this into a draft since we're evaluating the current impact of those path changes. If we confirm we want to move forward, I'll turn this back into a merge-able PR once we can confirm we want to move on with this. I would still appreciate a review so that, if confirmed, we can simply merge.

**Review by loiskilberg-da — APPROVED** [review]
Thanks!

**Comment by stefanobaghino-da** [comment]
As mentioned above, unforeseen consequences forced us to roll back the change that made this PR necessary. Closing. Thanks for taking the time anyway, luckily it was trivial. 🙇🏻‍♂️

**Pull request closed without merging**
