### PR TITLE
CANCELING: Testing rli plugin on a bunch of finance files -> docs process related

### PR DESCRIPTION
**Pull request by da-katmurp**
Lines 31-34 in `seup-sphinx-source-tree` rely on the `literalinclude` plugin.

I changed the first call to `rli` and it looks like it works well on the live preview but need someone to check it is actually working before sharing with Finance team.

Thank you.

(This is the easiest way to do a bulk test on this. All other options require too many script edits for comfort.)

We could even merge this one, if we can get it to deploy, the other ways no, but I will leave that to your decision @garyverhaegen-da

### CODE REVIEW

**Comment by da-katmurp** [comment]
OK, it failed but I guess I'm on a good track so maybe you can get this test to work @garyverhaegen-da ?

**Comment by garyverhaegen-da** [comment]
I'm a bit busy with other things right now but will take a look when I can.

**Comment by da-katmurp** [comment]
Perfect, there is no urgency :)

**Comment by garyverhaegen-da** [comment]
@da-katmurp Build now succeeds. Please double-check it looks as expected before merging.

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by da-katmurp** [comment]
For info @garyverhaegen-da I'm going to have to pause work on this until the other PR #120 is in

**Comment by da-katmurp** [comment]
Trello ticket for info: https://trello.com/c/9zEY2zPM

**Pull request closed without merging**
