### PR TITLE
HA & Scaling section ready for review.

### PR DESCRIPTION
**Pull request by da-katmurp**
The following files are ready for language/proof/formatting review.

Everything under `deploy-daml/infrastructure-architecture/high-availability/ha-and-scaling`, also `deploy-daml/infrastructure-architecture/disaster-recovery` and the related TOC entries.

TODO: the Canton files which I've put in a separate section.

### CODE REVIEW

**Comment by da-katmurp** [comment]
Related: waiting for snapshot: https://github.com/DACH-NY/canton/pull/11518

**Comment by da-katmurp** [comment]
Blocked by this PR: https://github.com/DACH-NY/canton/pull/11621

**Comment by garyverhaegen-da** [comment]
> Blocked by this PR: [DACH-NY/canton#11621](https://github.com/DACH-NY/canton/pull/11621)

Since we update Canton deliberately on this side, there is generally no need to block Canton PRs on docs PRs: we can merge the Canton side first, then update this side when convenient. In fact, due to the 24h delay it is generally better to merge the Canton side first.

Also, this PR is still marked "DO NOT REVIEW OR MERGE"; please update the title when merging becomes an option.

**Comment by da-katmurp** [comment]
> > Blocked by this PR: [DACH-NY/canton#11621](https://github.com/DACH-NY/canton/pull/11621)
> 
> Since we update Canton deliberately on this side, there is generally no need to block Canton PRs on docs PRs: we can merge the Canton side first, then update this side when convenient. In fact, due to the 24h delay it is generally better to merge the Canton side first.
> 
> Also, this PR is still marked "DO NOT REVIEW OR MERGE"; please update the title when merging becomes an option.

I'm blocked on a change in Canton that needs to go in and we can't do it here.

**Comment by da-katmurp** [comment]
> > > Blocked by this PR: [DACH-NY/canton#11621](https://github.com/DACH-NY/canton/pull/11621)
> > 
> > 
> > Since we update Canton deliberately on this side, there is generally no need to block Canton PRs on docs PRs: we can merge the Canton side first, then update this side when convenient. In fact, due to the 24h delay it is generally better to merge the Canton side first.
> > Also, this PR is still marked "DO NOT REVIEW OR MERGE"; please update the title when merging becomes an option.
> 
> I'm blocked on a change in Canton that needs to go in and we can't do it here.

I won't be ready to review or merge for a good while. I'm close to getting the bare content in but it will need checking for correctness and a careful review from tech writers. I'm blocked on pages coming in from Canton - see Issue - and an outstanding content change.

**Comment by garyverhaegen-da** [comment]
Ah, sorry, I misread that. I thought you meant the Canton PR was blocked on this one.

**Review by garyverhaegen-da — APPROVED** [review]
Approving with no review as requested; review will happen asynchronously by tech writers.

**Pull request merged**
