### PR TITLE
clean up download script

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
Reducing duplication in preparation for future improvements.

### CODE REVIEW

**Comment by garyverhaegen-da** [comment]
Small improvement here: if the downloads are already there, we don't re-download them.

**Review by da-katmurp — APPROVED** [review]
So we won't have to run download anymore at all?

**Comment by garyverhaegen-da** [comment]
Actually added a slightly bigger improvement: `build` and `live-preview` now automatically call `download` (which is "safe" as it no longer overwrites existing tarballs) so there should no longer be a use-case for calling `download` explicitly. Updated the README & CI scripts to match.

**Comment by garyverhaegen-da** [comment]
> So we won't have to run download anymore at all?

Exactly. It's not a huge thing, but one fewer step seems good.

**Comment by da-katmurp** [comment]
any chance of updating LATEST at the same time?

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da any chance of updating LATEST at the same time?

Same time as what?

**Comment by da-katmurp** [comment]
> > @garyverhaegen-da any chance of updating LATEST at the same time?
> 
> Same time as what?

A download would seem like the best moment to update LATEST.

**Pull request merged**
