### PR TITLE
release 2.8.3

### PR DESCRIPTION
**Pull request by garyverhaegen-da**

### CODE REVIEW

**Review by marciw-da — APPROVED** [review]

**Comment by wallacekelly-da** [comment]
FYI.. this is what I'm seeing:

image

image

**Comment by garyverhaegen-da** [comment]
This is expected right now as this is still building. It should sort itself out once the [build](https://app.circleci.com/pipelines/github/digital-asset/docs.daml.com/19286/workflows/2e7b547d-2ba7-4ec2-9ad9-6cea15a1369b/jobs/19960) is finished.

**Comment by garyverhaegen-da** [comment]
@wallacekelly-da The deployment is now done, please check again.

**Comment by wallacekelly-da** [comment]
@garyverhaegen-da All good! I just happened to hit it during the transition.

**Comment by wallacekelly-da** [comment]
@garyverhaegen-da Is this difference an expected transient issue?

image

**Comment by garyverhaegen-da** [comment]
No, there is nothing transient anymore. The 2.8.3 publication is fully finished. Note that [2.8.1](https://docs.daml.com/2.8.1/canton/usermanual/identity_management.html#replicate-party-to-another-participant-node) showed the same discrepancy.

Canton docs `snippet` directives are not direct inclusion, they go through a mapping from snippet name to content. You'll have to consult with the Canton team to know whether this discrepancy is expected here.

**Comment by garyverhaegen-da** [comment]
@wallacekelly-da This should have been fixed by #650. Please shout if it wasn't.

**Comment by wallacekelly-da** [comment]
Yes, the docs are correct now. Thank you for double-checking!

**Pull request merged**
