### PR TITLE
add new contention material

### PR DESCRIPTION
**Pull request by loiskilberg-da**
Add information on contention consisting of three new files. Adjust table of contents to include new files. Edit some related text and add links to the new content within three other existing files. This pull request will replace the outdated one at: https://github.com/digital-asset/docs.daml.com/pull/175

### CODE REVIEW

**Review by carrielaben-da — COMMENTED** [review]
These are all content changes (content changed in 2.6.4 should also be identically changed in 2.7.0, of course.) I will run live preview and check for formatting next.

**Review by carrielaben-da — COMMENTED** [review]
These are all content changes (content changed in 2.6.4 should also be identically changed in 2.7.0, of course.) I will run live preview and check for formatting next.

**Review by carrielaben-da — APPROVED** [review]
Formatting and link check complete - looks good!

**Review by loiskilberg-da — COMMENTED** [review]
make edits in 2.7.0 to match edits made for 2.6.4

**Pull request merged**
