### PR TITLE
Revert "release 2.4.2 docs (#82)"

### PR DESCRIPTION
**Pull request by garyverhaegen-da**
This reverts commit 2b2ce015d2f58c40a266a52b7b75621048846bce.

### CODE REVIEW

**Review by akrmn — APPROVED** [review]
😢

**Comment by garyverhaegen-da** [comment]
> 😢

Why the long face?

**Comment by akrmn** [comment]
because of the revert, but now it sounds like it's just part of the release process?

**Comment by garyverhaegen-da** [comment]
Yes. Not a great process by any means, but this is what we have right now.

**Pull request merged**
