### PR TITLE
remove vmware blockchain references

### PR DESCRIPTION
**Pull request by dasormeter**

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]

**Comment by rgugliel-da** [comment]
Can you rebase and do the corresponding changes in the new 2.9.0 version of the docs before merging ?

**Comment by dasormeter** [comment]
Okay maybe worth holding off on this until all the release stuff aettles (ot is just anminor textual cleanup so not super critical)

**Review by loiskilberg-da — APPROVED** [review]
thank you!

**Review by marciw-da — APPROVED** [review]
LGTM. (And thanks for waiting for the release dust to settle before merging)

**Pull request merged**
