### PR TITLE
Picking up latest snapshots

### PR DESCRIPTION
**Pull request by da-katmurp**
Continued delays in bringing new content in.
Current state -> PR raised in Canton on Monday and approved yesterday (Tuesday) is still building.

### CODE REVIEW

**Comment by da-katmurp** [comment]
Hi @gerolf-da a stamp on this one would be very helpful when you have time please, thank you.

**Comment by gerolf-da** [comment]
Is Pipfile needed? I thought this was managed by nix?

**Comment by da-katmurp** [comment]
I'm hoping Gary will add Pip configs to gitignore as they are popping up all over the place.

**Comment by da-katmurp** [comment]
Let's do this @gerolf-da  :)

**Comment by da-katmurp** [comment]
@garyverhaegen-da @gerolf-da this is a really dangerous fix of the build - in my view. The error comes from another PR, a completely different task, which is not finished and won't be finished for at least 2/3 weeks, maybe more. This means that 2.6.0 _has to include all these changes_ or there will be missing documentation, and it's impossible to track this.

**Comment by da-katmurp** [comment]
Update: this failure can't be fixed @garyverhaegen-da @gerolf-da.

**Pull request closed without merging**
