### PR TITLE
Use local bugfixed version of external toc plugin

### PR DESCRIPTION
**Pull request by bame-da**
This pulls in https://github.com/executablebooks/sphinx-external-toc/pull/88 and thus enables live-preview of ToC title changes.

### CODE REVIEW

**Review by garyverhaegen-da — APPROVED** [review]
Very unenthused by the addition of an opaque binary file like that. How was it produced?

**Comment by bame-da** [comment]
`flit build` on https://github.com/executablebooks/sphinx-external-toc/pull/88.
We could checkout the code pointing to a commit hash so I can't modify it anymore, and run `python -m pip install flint && flint install` to install from source.

**Comment by garyverhaegen-da** [comment]
> `flit build` on [executablebooks/sphinx-external-toc#88](https://github.com/executablebooks/sphinx-external-toc/pull/88).
> We could checkout the code pointing to a commit hash so I can't modify it anymore, and run `python -m pip install flint && flint install` to install from source.

I'd prefer that, yes, especially if there's a relatively easy way to do that within `.envrc` directly, with some way to check whether it needs to be done (i.e. it's been done already).

**Comment by bame-da** [comment]
@garyverhaegen-da I gave it a shot, but I do use direnv... Does this work for you?

**Comment by garyverhaegen-da** [comment]
> @garyverhaegen-da I gave it a shot, but I do use direnv... Does this work for you?

Yes, that's pretty much what I had in mind, sorry if I wasn't clear.

**Review by garyverhaegen-da — APPROVED** [review]

**Pull request merged**
