### PR TITLE
Fix scroll position for cross references links

### PR DESCRIPTION
**Pull request by wallacekelly-da**
You may have noticed a very annoying behavior when clicking on links within the Ledger API reference docs. For example, if you click on the link for the [GetActiveContractsResponse message](https://docs.daml.com/app-dev/grpc/proto-docs.html#com-daml-ledger-api-v1-getactivecontractsresponse), the heading for that message is _behind_ the navbar. It is very confusing for new users.

This PR makes a small CSS tweak to address that issue. Using jQuery, it dynamically adds the `section` CSS class to the `span`s which serve as the anchor for internal links.

I did look at trying to add that CSS class to the RST source file, but without success. I have also [asked on StackOverflow](https://stackoverflow.com/questions/79091778/add-css-class-to-sphinx-generated-anchor-span).

Attached are videos showing _before_ and _after_.

https://github.com/user-attachments/assets/a3963573-f321-499f-8dd7-3a13adaa8987

https://github.com/user-attachments/assets/66f9c6b1-a31c-4c1c-8e4b-73703a0550fd

### CODE REVIEW

**Review by carrielaben-da — APPROVED** [review]
LGTM

**Comment by yves-da** [comment]
Oh nice!

This is however a general problem on docs.daml.com, see
* https://github.com/digital-asset/docs.daml.com/issues/722

Not sure how easy it would be to apply this fix generally 🤔

**Comment by wallacekelly-da** [comment]
> Not sure how easy it would be to apply this fix generally

@yves-da, with 91f6986ab81014dfcbc9728432e5e59ef39dac26 I changed the jQuery selector from `span[id^=com-daml-ledger-api-v]` to `div.section > span`.

* The former selects spans whose ids start with `com-daml-ledger-api-v`.
* The latter selects spans that are direct children of a `div` with the class `section`. This is the pattern that Sphinx uses, as described [here](https://stackoverflow.com/q/79091778/167920).

With the new selector, the issue seems to be addressed site wide.

**Comment by yves-da** [comment]
@wallacekelly-da thanks a lot for the fix.

> With the new selector, the issue seems to be addressed site wide.
I wasn't able to verify that for myself. However, since this is `theme`-only change CI didn't update docs.daml.com because of https://github.com/digital-asset/docs.daml.com/issues/758

**Comment by yves-da** [comment]
And indeed, after docs/2.10.0 got updated from another PR, the improvement materialized for that version. Very nice 😆

**Pull request merged**
