### PR TITLE
Restructure `Instrument modeling` section

### PR DESCRIPTION
**Pull request by matteolimberto-da**
Fixes https://github.com/digital-asset/daml-finance/issues/809

Keen to hear your opinion on this change @markus-da, as we discussed it while you were on holiday.

The rationale for this is the fact that
- `Instrument modeling` currently contains many things, not all related to instrument modeling
- I need a section where I can put the contingent claims documentation we discussed before your holiday

Instrument modeling is broken into
- Instrument packages --> how to use existing instrument packages
- payoff modeling --> this is where CC doc will go, i'm considering calling this "Custom payoff modeling"
- Advanced Topics --> stuff like intermediated lifecycling or how to create your own dynamic claim instrument

### CODE REVIEW

**Comment by markus-da** [comment]
I think this new structure makes sense.

**Comment by markus-da** [comment]
> * payoff modeling --> this is where CC doc will go, i'm considering calling this "Custom payoff modeling"

Not sure I would use Custom, because maybe it indicates that it concerns Generic instruments, which are kind of custom payoffs? I think it is important to keep the CC doc quite general, so that it describes the basics both to write Generic instruments as well as dynamic instruments.

**Comment by matteolimberto-da** [comment]
> I think this new structure makes sense.

Thanks, I marked as ready for review

**Review by markus-da — APPROVED** [review]
LGTM

**Pull request merged**
